# Generated by Django 5.1.1 on 2024-10-17 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_on', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CarCharger',
            fields=[
                ('smartdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homeapp.smartdevice')),
                ('is_connected_to_car', models.BooleanField(default=False)),
                ('power_consumption', models.IntegerField(default=0)),
                ('total_power_consumption', models.IntegerField(default=0)),
            ],
            bases=('homeapp.smartdevice',),
        ),
        migrations.CreateModel(
            name='SmartBulb',
            fields=[
                ('smartdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homeapp.smartdevice')),
                ('brightness', models.IntegerField(default=100)),
                ('color', models.CharField(default='white', max_length=20)),
            ],
            bases=('homeapp.smartdevice',),
        ),
        migrations.CreateModel(
            name='SmartThermostat',
            fields=[
                ('smartdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homeapp.smartdevice')),
                ('temperature_in_room', models.IntegerField()),
                ('humidity', models.IntegerField()),
            ],
            bases=('homeapp.smartdevice',),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='smartdevice',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.home'),
        ),
    ]
