# Generated by Django 5.1.1 on 2024-10-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthermostat',
            name='mode',
            field=models.CharField(choices=[('cool', 'Cooling'), ('heat', 'Heating'), ('off', 'Off')], default='off', max_length=10),
        ),
    ]
