# Generated by Django 5.1.1 on 2024-10-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_smartthermostat_set_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcharger',
            name='car_battery_capacity',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='carcharger',
            name='car_battery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carcharger',
            name='is_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carcharger',
            name='max_power_output',
            field=models.IntegerField(default=60),
        ),
    ]
