# Generated by Django 5.1.1 on 2024-11-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_home_lat_home_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartthermostat',
            name='temperature_in_room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
