# Generated by Django 5.1.1 on 2024-11-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_alter_smartthermostat_temperature_in_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartthermostat',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
