# Generated by Django 5.1.1 on 2024-11-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_carcharger_device_type_smartbulb_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcharger',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='smartbulb',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='smartthermostat',
            name='device_type',
        ),
        migrations.AddField(
            model_name='smartdevice',
            name='device_type',
            field=models.CharField(default='smartdevice', max_length=50),
        ),
    ]
