@startuml
'https://plantuml.com/state-diagram

hide empty description

state "Action Car Carger" as actioncarcharg
[*] --> actioncarcharg

state Check_Car_Connected {
[*] --> Communicate_Car
Communicate_Car --> Success
Communicate_Car --> UnSuccess
UnSuccess --> Error_message
Error_message --> Communicate_Car : try again
Success --> message_use
}



state Start_Charging {
charging_state --> send_charging_message
send_charging_message --> start_charing
}

state Stop_Charging {

Stopping0 --> save_stop0
save_stop0 --> Communicate_Car0
save_stop0 --> message_user0
Communicate_Car0 --> UnSuccess0
UnSuccess0 --> Error_message0
Error_message0 --> Communicate_Car0
}

actioncarcharg --> Check_Car_Connected
Check_Car_Connected --> Start_Charging
Check_Car_Connected --> Stop_Charging



@enduml